version: '3.9'

services:
  db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    # volumes:
    #   - pgdata:/var/lib/postgresql/data

  server:
    build:
      context: .
      dockerfile: deployments/Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - db
  
# volumes:
#   pgdata: